apiVersion: apps/v1
kind: Deployment
metadata:
  name: prediction-service
  labels:
    app: prediction-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prediction-service
  template:
    metadata:
      labels:
        app: prediction-service
    spec:
      containers:
      - name: prediction-service
        image: prediction-service:1.0
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: model-volume
          mountPath: /app/model.pkl
          subPath: model.pkl
      volumes:
      - name: model-volume
        hostPath:
          path: /path/on/host/model.pkl
          type: File
