global:
  scrape_interval: 15s  # Set the scrape interval to every 15 seconds.

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'docker'
    scrape_interval: 5s
    static_configs:
      - targets: ['<docker-service-name>:<port>']
